import { ROLES, Role } from "./roles";
import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.LEAVE_VIEW,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,

    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_DELETE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.TASK_VIEW,

    PERMISSIONS.PAYROLL_VIEW,

    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.ACCOUNTS]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,

    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  [ROLES.CEO]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,

    PERMISSIONS.TASK_VIEW,

    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.PAYROLL_VIEW,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.SETTINGS_MANAGE,
  ],
};